test = {
    'Navigate to profile': function (browser) {
        browser
            .click(".eventsMenuIcon")
            .pause(100)
            .assert.visible(".profileButton")
            .pause(100)
            .click(".profileButton")
            .pause(500)
            .assert.title("Profile")
            .assert.containsText(".profileName", "Test Salad")

    },
    'Buy Credits' : function(browser){
        browser
            .click(".claimsBtn")
            .assert.visible(".claimsTitle")
            .assert.containsText(".claimsTitle", "Buy Claims")
            .assert.value("#inputNumber", "0")
            .pause(300)
            .click(".claimsO1")
            .pause(300)
            .assert.value("#inputNumber", "100")
            .click(".claimsO2")
            .pause(300)
            .assert.value("#inputNumber", "350")
            .click(".claimsO3")
            .pause(300)
            .assert.value("#inputNumber", "850")
            .click(".claimsO4")
            .pause(300)
            .assert.value("#inputNumber", "1850")
            .setValue('#inputNumber', browser.Keys.BACK_SPACE)
            .setValue('#inputNumber', browser.Keys.BACK_SPACE)
            .setValue('#inputNumber', browser.Keys.BACK_SPACE)
            .setValue('#inputNumber', browser.Keys.BACK_SPACE)
            .setValue('#inputNumber', '0')
            .pause(200)
            .click(".claimsMore")
            .assert.value("#inputNumber", "10")
            .click(".claimsLess")
            .assert.value("#inputNumber", "0")
            .setValue('#inputNumber', '4')
            .click(".creditCardButton")
            .pause(500)
            .assert.visible(".creditCardsHeading")
            .assert.containsText(".creditCardsHeading", "My Cards")
            .pause(100)
            .click('div[ng-click="buyCredits.addNewCard()"]')
            .pause(300)
            .assert.containsText(".cardInstructions", "Enter your details")
            .setValue("#cardNumber", "4875637234")
            .setValue(".addCardNameInput input", "Not-A-Bank Bank")
            .setValue(".addCardExpiryInput input", "2020")
            .setValue("#cardCVC", "123")
            .pause(100)
            .click(".buttonAddCard")
            .verify.containsText(".cardInstructions", "Your card number must be 16 digits")
            .setValue("#cardNumber", "8475" + Math.floor((Math.random() * 10)) + Math.floor((Math.random() * 10)))
            .pause(100)
            .click(".buttonAddCard")
            .pause(100)
            .verify.containsText(".cardInstructions", "Please enter the expiry date")
            .setValue(".addCardExpiryInput input", "-12")
            .pause(100)
            .click(".buttonAddCard")
            .pause(100)
            .assert.visible(".creditCardsScrollContent > div:nth-child(1) > div:nth-child(1)")
            .click(".creditCardsScrollContent > div:nth-child(1) > div:nth-child(1)")
            .pause(100)
            .click(".claimsExit")
            .pause(500)
            .click(".menuIcon")
            .pause(300)
            .click("#profileMenu > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1)")
            .pause(500)
    }
};